
- hosts: webserver
  gather_facts: false
  become: true
  become_user: root
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python2-minimal)
- hosts: webserver
  roles:
  - server
  - php
  - mysql
  - wordpress


